<a href="https://colab.research.google.com/github/gopikasingh/gopika/blob/master/Data_Pre-Processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [ ]:
read_file = pd.read_excel ("filee.xlsx")
read_file.to_csv ("neww.csv", 
                  index = None,
                  header=True)

In [ ]:
df = pd.DataFrame(pd.read_csv("neww.csv"))
df

          EAN CODE      STYLE CODE      ART NAME    COLOR  SIZE  QTY
0    8905334084233  GL001BLK         469060383001   BLACK     6     5
1    8905334084226  GL001BLK         469060383002   BLACK     7    10
2    8905334084219  GL001BLK         469060383003   BLACK     8    15
3    8905334084202  GL001BLK         469060383004   BLACK     9    15
4    8905334084196  GL001BLK         469060383005   BLACK    10    10
..             ...              ...           ...     ...   ...   ...
163  8905334083922  GL011TAN         469060388002     TAN     7    14
164  8905334083915  GL011TAN         469060388003     TAN     8    21
165  8905334083908  GL011TAN         469060388004     TAN     9    21
166  8905334083892  GL011TAN         469060388005     TAN    10    14
167  8905334083885  GL011TAN         469060388006     TAN    11     7

[168 rows x 6 columns]

In [ ]:
arr = []
arr = [[0] for i in range(168)]
print(arr, len(arr))

[[0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0]] 168

In [ ]:

df.insert(6, "cartons", arr, True)

In [ ]:
df

          EAN CODE      STYLE CODE      ART NAME    COLOR  SIZE  QTY  cartons
0    8905334084233  GL001BLK         469060383001   BLACK     6     5     [0]
1    8905334084226  GL001BLK         469060383002   BLACK     7    10     [0]
2    8905334084219  GL001BLK         469060383003   BLACK     8    15     [0]
3    8905334084202  GL001BLK         469060383004   BLACK     9    15     [0]
4    8905334084196  GL001BLK         469060383005   BLACK    10    10     [0]
..             ...              ...           ...     ...   ...   ...     ...
163  8905334083922  GL011TAN         469060388002     TAN     7    14     [0]
164  8905334083915  GL011TAN         469060388003     TAN     8    21     [0]
165  8905334083908  GL011TAN         469060388004     TAN     9    21     [0]
166  8905334083892  GL011TAN         469060388005     TAN    10    14     [0]
167  8905334083885  GL011TAN         469060388006     TAN    11     7     [0]

[168 rows x 7 columns]

In [ ]:
df.columns

Index(['EAN CODE', 'STYLE CODE ', 'ART NAME ', 'COLOR', 'SIZE', 'QTY ',
       'cartons'],
      dtype='object')

In [ ]:
df.cartons[0] = [0]
df = df.rename(columns={'QTY ': 'qty', 'EAN CODE':'ean', 'STYLE CODE ':'stylee', 'ART NAME ':'art'})

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
df

               ean           stylee           art   COLOR  SIZE  qty cartons
0    8905334084233  GL001BLK         469060383001   BLACK     6    5     [0]
1    8905334084226  GL001BLK         469060383002   BLACK     7   10     [0]
2    8905334084219  GL001BLK         469060383003   BLACK     8   15     [0]
3    8905334084202  GL001BLK         469060383004   BLACK     9   15     [0]
4    8905334084196  GL001BLK         469060383005   BLACK    10   10     [0]
..             ...              ...           ...     ...   ...  ...     ...
163  8905334083922  GL011TAN         469060388002     TAN     7   14     [0]
164  8905334083915  GL011TAN         469060388003     TAN     8   21     [0]
165  8905334083908  GL011TAN         469060388004     TAN     9   21     [0]
166  8905334083892  GL011TAN         469060388005     TAN    10   14     [0]
167  8905334083885  GL011TAN         469060388006     TAN    11    7     [0]

[168 rows x 7 columns]

In [ ]:
df1 = df.copy()
no = 0

In [ ]:
space = 10
fir = 1
prev = df.stylee[0]
for x in range(0, 168):
  if prev == df.stylee[x]:
    curr = df1.qty[x]
    if curr < space:
      df1.cartons[x] = fir
      space = space - curr
    else:
      #line = DataFrame({"onset": 30.0, "length": 1.3}, index=[3])
      #df2 = concat([df.iloc[:2], line, df.iloc[2:]]).reset_index(drop=True)
      line = pd.DataFrame({"ean":df1.ean[x], "stylee":df1.stylee[x], "art":df1.art[x], "COLOR":df1.COLOR[x], "SIZE":df1.SIZE[x], "qty":space, "cartons":fir}, index=[x])
      df1 = pd.concat([df1.iloc[:x], line, df1.iloc[x:]]).reset_index(drop=True)
      df1.qty[x+1] = curr-space
      df1.cartons[x+1] = fir+1
      #df1.loc[x+1] = [df1.ean[x], df1.stylee[x], df1.art[x], df1.COLOR[x], df1.SIZE[x], curr-space, fir]
      fir += 1
      space = 10
  else:
    prev = df.stylee[x]
    fir +=1
    #print(space)
    space = 10
  print(df.qty[x],"-",space)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()

5 - 5
10 - 10
15 - 5
15 - 10
10 - 10
5 - 10
7 - 10
14 - 10
21 - 10
21 - 5
14 - 10
7 - 8
7 - 10
14 - 10
21 - 10
21 - 9
14 - 10
7 - 10
5 - 10
10 - 10
15 - 6
15 - 10
10 - 9
5 - 2
7 - 10
14 - 10
21 - 10
21 - 9
14 - 10
7 - 10
7 - 10
14 - 10
21 - 6
21 - 10
14 - 9
7 - 4
5 - 10
10 - 10
15 - 5
15 - 10
10 - 10
5 - 10
5 - 10
10 - 5
15 - 10
15 - 8
10 - 10
5 - 4
10 - 10
20 - 10
30 - 10
30 - 9
20 - 10
10 - 5
10 - 10
20 - 3
30 - 10
30 - 10
20 - 9
10 - 10
5 - 10
10 - 10
15 - 10
15 - 9
10 - 10
5 - 5
7 - 10
14 - 5
21 - 10
21 - 5
14 - 10
7 - 10
6 - 10
12 - 10
18 - 5
18 - 10
12 - 5
6 - 10
5 - 10
10 - 5
15 - 10
15 - 5
10 - 10
5 - 10
5 - 10
10 - 10
15 - 5
15 - 10
10 - 5
5 - 10
5 - 10
10 - 10
15 - 10
15 - 10
10 - 10
5 - 10
7 - 10
14 - 10
21 - 10
21 - 10
14 - 10
7 - 10
5 - 10
10 - 10
15 - 10
15 - 10
10 - 10
5 - 10
10 - 10
20 - 10
30 - 10
30 - 10
20 - 10
10 - 10
10 - 10
20 - 10
30 - 10
30 - 10
20 - 10
10 - 10
10 - 10
20 - 10
30 - 10
30 - 10
20 - 5
10 - 10
5 - 10
10 - 10
15 - 10
15 - 5
10 - 10
5 - 8
5 - 10
10 - 10
15 - 10
15 - 9
10 - 10
5 - 10
7 - 10
14 - 10
21 - 6
21 - 10
14 - 9
7 - 3
7 - 10
14 - 10
21 - 2
21 - 10
14 - 10
7 - 4
5 - 10
10 - 4
15 - 10
15 - 9
10 - 10
5 - 9
7 - 10
14 - 10
21 - 5
21 - 10
14 - 5
7 - 10
7 - 10
14 - 5
21 - 10
21 - 5
14 - 10
7 - 10

In [ ]:
print(df1.to_markdown())

|     |           ean | stylee   |          art | COLOR   |   SIZE |   qty | cartons   |
|----:|--------------:|:---------|-------------:|:--------|-------:|------:|:----------|
|   0 | 8905334084233 | GL001BLK | 469060383001 | BLACK   |      6 |     5 | 1         |
|   1 | 8905334084226 | GL001BLK | 469060383002 | BLACK   |      7 |     5 | 1         |
|   2 | 8905334084226 | GL001BLK | 469060383002 | BLACK   |      7 |     5 | 2         |
|   3 | 8905334084219 | GL001BLK | 469060383003 | BLACK   |      8 |     5 | 2         |
|   4 | 8905334084219 | GL001BLK | 469060383003 | BLACK   |      8 |    10 | 3         |
|   5 | 8905334084219 | GL001BLK | 469060383003 | BLACK   |      8 |     0 | 4         |
|   6 | 8905334084202 | GL001BLK | 469060383004 | BLACK   |      9 |    15 | [0]       |
|   7 | 8905334084196 | GL001BLK | 469060383005 | BLACK   |     10 |    10 | 5         |
|   8 | 8905334084196 | GL001BLK | 469060383005 | BLACK   |     10 |     0 | 6         |
|   9 | 8905334084189 | GL001BLK | 469060383006 | BLACK   |     11 |     5 | 6         |
|  10 | 8905334084172 | GL001BRN | 469060384001 | BROWN   |      6 |     5 | 6         |
|  11 | 8905334084172 | GL001BRN | 469060384001 | BROWN   |      6 |     2 | 7         |
|  12 | 8905334084165 | GL001BRN | 469060384002 | BROWN   |      7 |    14 | [0]       |
|  13 | 8905334084158 | GL001BRN | 469060384003 | BROWN   |      8 |    10 | 8         |
|  14 | 8905334084158 | GL001BRN | 469060384003 | BROWN   |      8 |    10 | 9         |
|  15 | 8905334084158 | GL001BRN | 469060384003 | BROWN   |      8 |     1 | 10        |
|  16 | 8905334084141 | GL001BRN | 469060384004 | BROWN   |      9 |     9 | 10        |
|  17 | 8905334084141 | GL001BRN | 469060384004 | BROWN   |      9 |    10 | 11        |
|  18 | 8905334084141 | GL001BRN | 469060384004 | BROWN   |      9 |     2 | 12        |
|  19 | 8905334084134 | GL001BRN | 469060384005 | BROWN   |     10 |    10 | 13        |
|  20 | 8905334084134 | GL001BRN | 469060384005 | BROWN   |     10 |     4 | 14        |
|  21 | 8905334084127 | GL001BRN | 469060384006 | BROWN   |     11 |     6 | 14        |
|  22 | 8905334084127 | GL001BRN | 469060384006 | BROWN   |     11 |     1 | 15        |
|  23 | 8905334084110 | GL001TAN | 469060385001 | TAN     |      6 |     7 | 15        |
|  24 | 8905334084103 | GL001TAN | 469060385002 | TAN     |      7 |    14 | [0]       |
|  25 | 8905334084097 | GL001TAN | 469060385003 | TAN     |      8 |    10 | 16        |
|  26 | 8905334084097 | GL001TAN | 469060385003 | TAN     |      8 |    10 | 17        |
|  27 | 8905334084097 | GL001TAN | 469060385003 | TAN     |      8 |     1 | 18        |
|  28 | 8905334084080 | GL001TAN | 469060385004 | TAN     |      9 |     9 | 18        |
|  29 | 8905334084080 | GL001TAN | 469060385004 | TAN     |      9 |    10 | 19        |
|  30 | 8905334084080 | GL001TAN | 469060385004 | TAN     |      9 |     2 | 20        |
|  31 | 8905334084073 | GL001TAN | 469060385005 | TAN     |     10 |    10 | 21        |
|  32 | 8905334084073 | GL001TAN | 469060385005 | TAN     |     10 |     4 | 22        |
|  33 | 8905334084066 | GL001TAN | 469060385006 | TAN     |     11 |     6 | 22        |
|  34 | 8905334084066 | GL001TAN | 469060385006 | TAN     |     11 |     1 | 23        |
|  35 | 8905334083878 | GL021BLK | 469060389001 | BLACK   |      6 |     5 | 23        |
|  36 | 8905334083861 | GL021BLK | 469060389002 | BLACK   |      7 |    10 | [0]       |
|  37 | 8905334083854 | GL021BLK | 469060389003 | BLACK   |      8 |    10 | 24        |
|  38 | 8905334083854 | GL021BLK | 469060389003 | BLACK   |      8 |     5 | 25        |
|  39 | 8905334083847 | GL021BLK | 469060389004 | BLACK   |      9 |     5 | 25        |
|  40 | 8905334083847 | GL021BLK | 469060389004 | BLACK   |      9 |    10 | 26        |
|  41 | 8905334083847 | GL021BLK | 469060389004 | BLACK   |      9 |     0 | 27        |
|  42 | 8905334083830 | GL021BLK | 469060389005 | BLACK   |     10 |    10 | [0]       |
|  43 | 8905334083823 | GL021BLK | 469060389006 | BLACK   |     11 |     5 | 28        |
|  44 | 8905334083816 | GL021BRN | 469060390001 | BROWN   |      6 |     5 | 28        |
|  45 | 8905334083816 | GL021BRN | 469060390001 | BROWN   |      6 |     2 | 29        |
|  46 | 8905334083809 | GL021BRN | 469060390002 | BROWN   |      7 |     8 | 29        |
|  47 | 8905334083809 | GL021BRN | 469060390002 | BROWN   |      7 |     6 | 30        |
|  48 | 8905334083793 | GL021BRN | 469060390003 | BROWN   |      8 |    21 | [0]       |
|  49 | 8905334083786 | GL021BRN | 469060390004 | BROWN   |      9 |    10 | 31        |
|  50 | 8905334083786 | GL021BRN | 469060390004 | BROWN   |      9 |    10 | 32        |
|  51 | 8905334083786 | GL021BRN | 469060390004 | BROWN   |      9 |     1 | 33        |
|  52 | 8905334083779 | GL021BRN | 469060390005 | BROWN   |     10 |     9 | 33        |
|  53 | 8905334083779 | GL021BRN | 469060390005 | BROWN   |     10 |     5 | 34        |
|  54 | 8905334083762 | GL021BRN | 469060390006 | BROWN   |     11 |     7 | [0]       |
|  55 | 8905334083755 | GL021TAN | 469060391001 | TAN     |      6 |     7 | 35        |
|  56 | 8905334083748 | GL021TAN | 469060391002 | TAN     |      7 |     3 | 35        |
|  57 | 8905334083748 | GL021TAN | 469060391002 | TAN     |      7 |    10 | 36        |
|  58 | 8905334083748 | GL021TAN | 469060391002 | TAN     |      7 |     1 | 37        |
|  59 | 8905334083731 | GL021TAN | 469060391003 | TAN     |      8 |     9 | 37        |
|  60 | 8905334083731 | GL021TAN | 469060391003 | TAN     |      8 |    12 | 38        |
|  61 | 8905334083724 | GL021TAN | 469060391004 | TAN     |      9 |    10 | 39        |
|  62 | 8905334083724 | GL021TAN | 469060391004 | TAN     |      9 |    10 | 40        |
|  63 | 8905334083724 | GL021TAN | 469060391004 | TAN     |      9 |     1 | 41        |
|  64 | 8905334083717 | GL021TAN | 469060391005 | TAN     |     10 |     9 | 41        |
|  65 | 8905334083717 | GL021TAN | 469060391005 | TAN     |     10 |     5 | 42        |
|  66 | 8905334083700 | GL021TAN | 469060391006 | TAN     |     11 |     7 | [0]       |
|  67 | 8905334083694 | GL031BRN | 469060392001 | BROWN   |      6 |     5 | 43        |
|  68 | 8905334083687 | GL031BRN | 469060392002 | BROWN   |      7 |     5 | 43        |
|  69 | 8905334083687 | GL031BRN | 469060392002 | BROWN   |      7 |     5 | 44        |
|  70 | 8905334083670 | GL031BRN | 469060392003 | BROWN   |      8 |     5 | 44        |
|  71 | 8905334083670 | GL031BRN | 469060392003 | BROWN   |      8 |    10 | 45        |
|  72 | 8905334083670 | GL031BRN | 469060392003 | BROWN   |      8 |     0 | 46        |
|  73 | 8905334083663 | GL031BRN | 469060392004 | BROWN   |      9 |    10 | 47        |
|  74 | 8905334083663 | GL031BRN | 469060392004 | BROWN   |      9 |     5 | 48        |
|  75 | 8905334083656 | GL031BRN | 469060392005 | BROWN   |     10 |     5 | 48        |
|  76 | 8905334083656 | GL031BRN | 469060392005 | BROWN   |     10 |     5 | 49        |
|  77 | 8905334083649 | GL031BRN | 469060392006 | BROWN   |     11 |     5 | 49        |
|  78 | 8905334083649 | GL031BRN | 469060392006 | BROWN   |     11 |     0 | 50        |
|  79 | 8905334083632 | GL031TAN | 469060393001 | TAN     |      6 |     5 | 51        |
|  80 | 8905334083625 | GL031TAN | 469060393002 | TAN     |      7 |     5 | 51        |
|  81 | 8905334083625 | GL031TAN | 469060393002 | TAN     |      7 |     5 | 52        |
|  82 | 8905334083618 | GL031TAN | 469060393003 | TAN     |      8 |     5 | 52        |
|  83 | 8905334083618 | GL031TAN | 469060393003 | TAN     |      8 |    10 | 53        |
|  84 | 8905334083618 | GL031TAN | 469060393003 | TAN     |      8 |     0 | 54        |
|  85 | 8905334083601 | GL031TAN | 469060393004 | TAN     |      9 |    10 | 55        |
|  86 | 8905334083601 | GL031TAN | 469060393004 | TAN     |      9 |     5 | 56        |
|  87 | 8905334083595 | GL031TAN | 469060393005 | TAN     |     10 |     5 | 56        |
|  88 | 8905334083595 | GL031TAN | 469060393005 | TAN     |     10 |     5 | 57        |
|  89 | 8905334083588 | GL031TAN | 469060393006 | TAN     |     11 |     5 | 57        |
|  90 | 8905334083588 | GL031TAN | 469060393006 | TAN     |     11 |     0 | 58        |
|  91 | 8905334083571 | GL041BLK | 469060394001 | BLACK   |      6 |    10 | 59        |
|  92 | 8905334083571 | GL041BLK | 469060394001 | BLACK   |      6 |     0 | 60        |
|  93 | 8905334083564 | GL041BLK | 469060394002 | BLACK   |      7 |    10 | 60        |
|  94 | 8905334083564 | GL041BLK | 469060394002 | BLACK   |      7 |    10 | 61        |
|  95 | 8905334083564 | GL041BLK | 469060394002 | BLACK   |      7 |     0 | 62        |
|  96 | 8905334083557 | GL041BLK | 469060394003 | BLACK   |      8 |    30 | [0]       |
|  97 | 8905334083540 | GL041BLK | 469060394004 | BLACK   |      9 |    10 | 63        |
|  98 | 8905334083540 | GL041BLK | 469060394004 | BLACK   |      9 |    10 | 64        |
|  99 | 8905334083540 | GL041BLK | 469060394004 | BLACK   |      9 |    10 | 65        |
| 100 | 8905334083540 | GL041BLK | 469060394004 | BLACK   |      9 |     0 | 66        |
| 101 | 8905334083533 | GL041BLK | 469060394005 | BLACK   |     10 |    10 | 66        |
| 102 | 8905334083533 | GL041BLK | 469060394005 | BLACK   |     10 |    10 | 67        |
| 103 | 8905334083526 | GL041BLK | 469060394006 | BLACK   |     11 |    10 | 68        |
| 104 | 8905334083526 | GL041BLK | 469060394006 | BLACK   |     11 |     0 | 69        |
| 105 | 8905334083519 | GL051BRN | 469060395001 | BROWN   |      6 |    10 | 69        |
| 106 | 8905334083519 | GL051BRN | 469060395001 | BROWN   |      6 |     0 | 70        |
| 107 | 8905334083502 | GL051BRN | 469060395002 | BROWN   |      7 |    10 | 70        |
| 108 | 8905334083502 | GL051BRN | 469060395002 | BROWN   |      7 |    10 | 71        |
| 109 | 8905334083496 | GL051BRN | 469060395003 | BROWN   |      8 |    10 | 72        |
| 110 | 8905334083496 | GL051BRN | 469060395003 | BROWN   |      8 |    10 | 73        |
| 111 | 8905334083496 | GL051BRN | 469060395003 | BROWN   |      8 |    10 | 74        |
| 112 | 8905334083496 | GL051BRN | 469060395003 | BROWN   |      8 |     0 | 75        |
| 113 | 8905334083489 | GL051BRN | 469060395004 | BROWN   |      9 |    10 | 75        |
| 114 | 8905334083489 | GL051BRN | 469060395004 | BROWN   |      9 |    20 | 76        |
| 115 | 8905334083472 | GL051BRN | 469060395005 | BROWN   |     10 |    10 | 77        |
| 116 | 8905334083472 | GL051BRN | 469060395005 | BROWN   |     10 |    10 | 78        |
| 117 | 8905334083472 | GL051BRN | 469060395005 | BROWN   |     10 |     0 | 79        |
| 118 | 8905334083465 | GL051BRN | 469060395006 | BROWN   |     11 |    10 | 79        |
| 119 | 8905334083465 | GL051BRN | 469060395006 | BROWN   |     11 |     0 | 80        |
| 120 | 8905334083458 | GL061BLK | 469060396001 | BLACK   |      6 |     5 | [0]       |
| 121 | 8905334083441 | GL061BLK | 469060396002 | BLACK   |      7 |    10 | 81        |
| 122 | 8905334083441 | GL061BLK | 469060396002 | BLACK   |      7 |     0 | 82        |
| 123 | 8905334083434 | GL061BLK | 469060396003 | BLACK   |      8 |    10 | 82        |
| 124 | 8905334083434 | GL061BLK | 469060396003 | BLACK   |      8 |     5 | 83        |
| 125 | 8905334083427 | GL061BLK | 469060396004 | BLACK   |      9 |     5 | 83        |
| 126 | 8905334083427 | GL061BLK | 469060396004 | BLACK   |      9 |    10 | 84        |
| 127 | 8905334083410 | GL061BLK | 469060396005 | BLACK   |     10 |    10 | 85        |
| 128 | 8905334083410 | GL061BLK | 469060396005 | BLACK   |     10 |     0 | 86        |
| 129 | 8905334083403 | GL061BLK | 469060396006 | BLACK   |     11 |     5 | 86        |
| 130 | 8905334083397 | GL061BRN | 469060397001 | BROWN   |      6 |     5 | 86        |
| 131 | 8905334083397 | GL061BRN | 469060397001 | BROWN   |      6 |     2 | 87        |
| 132 | 8905334083380 | GL061BRN | 469060397002 | BROWN   |      7 |    14 | [0]       |
| 133 | 8905334083373 | GL061BRN | 469060397003 | BROWN   |      8 |    10 | 88        |
| 134 | 8905334083373 | GL061BRN | 469060397003 | BROWN   |      8 |    10 | 89        |
| 135 | 8905334083373 | GL061BRN | 469060397003 | BROWN   |      8 |     1 | 90        |
| 136 | 8905334083366 | GL061BRN | 469060397004 | BROWN   |      9 |     9 | 90        |
| 137 | 8905334083366 | GL061BRN | 469060397004 | BROWN   |      9 |    10 | 91        |
| 138 | 8905334083366 | GL061BRN | 469060397004 | BROWN   |      9 |     2 | 92        |
| 139 | 8905334083359 | GL061BRN | 469060397005 | BROWN   |     10 |    10 | 93        |
| 140 | 8905334083359 | GL061BRN | 469060397005 | BROWN   |     10 |     4 | 94        |
| 141 | 8905334083342 | GL061BRN | 469060397006 | BROWN   |     11 |     6 | 94        |
| 142 | 8905334083342 | GL061BRN | 469060397006 | BROWN   |     11 |     1 | 95        |
| 143 | 8905334083335 | GL061TAN | 469060398001 | TAN     |      6 |     6 | 95        |
| 144 | 8905334083328 | GL061TAN | 469060398002 | TAN     |      7 |    12 | [0]       |
| 145 | 8905334083311 | GL061TAN | 469060398003 | TAN     |      8 |    10 | 96        |
| 146 | 8905334083311 | GL061TAN | 469060398003 | TAN     |      8 |     8 | 97        |
| 147 | 8905334083304 | GL061TAN | 469060398004 | TAN     |      9 |     2 | 97        |
| 148 | 8905334083304 | GL061TAN | 469060398004 | TAN     |      9 |    10 | 98        |
| 149 | 8905334083304 | GL061TAN | 469060398004 | TAN     |      9 |     6 | 99        |
| 150 | 8905334083298 | GL061TAN | 469060398005 | TAN     |     10 |    12 | [0]       |
| 151 | 8905334083281 | GL061TAN | 469060398006 | TAN     |     11 |     6 | 100       |
| 152 | 8905334083274 | GL071BLK | 469060399001 | BLACK   |      6 |     4 | 100       |
| 153 | 8905334083274 | GL071BLK | 469060399001 | BLACK   |      6 |     1 | 101       |
| 154 | 8905334083267 | GL071BLK | 469060399002 | BLACK   |      7 |     9 | 101       |
| 155 | 8905334083267 | GL071BLK | 469060399002 | BLACK   |      7 |     1 | 102       |
| 156 | 8905334083250 | GL071BLK | 469060399003 | BLACK   |      8 |    15 | [0]       |
| 157 | 8905334083243 | GL071BLK | 469060399004 | BLACK   |      9 |    10 | 103       |
| 158 | 8905334083243 | GL071BLK | 469060399004 | BLACK   |      9 |     5 | 104       |
| 159 | 8905334083236 | GL071BLK | 469060399005 | BLACK   |     10 |     5 | 104       |
| 160 | 8905334083236 | GL071BLK | 469060399005 | BLACK   |     10 |     5 | 105       |
| 161 | 8905334083229 | GL071BLK | 469060399006 | BLACK   |     11 |     5 | 105       |
| 162 | 8905334083229 | GL071BLK | 469060399006 | BLACK   |     11 |     0 | 106       |
| 163 | 8905334083212 | GL071BRN | 469060400001 | BROWN   |      6 |     5 | 107       |
| 164 | 8905334083205 | GL071BRN | 469060400002 | BROWN   |      7 |     5 | 107       |
| 165 | 8905334083205 | GL071BRN | 469060400002 | BROWN   |      7 |     5 | 108       |
| 166 | 8905334083199 | GL071BRN | 469060400003 | BROWN   |      8 |     5 | 108       |
| 167 | 8905334083199 | GL071BRN | 469060400003 | BROWN   |      8 |    10 | 109       |
| 168 | 8905334083199 | GL071BRN | 469060400003 | BROWN   |      8 |     0 | 110       |
| 169 | 8905334083182 | GL071BRN | 469060400004 | BROWN   |      9 |    15 | [0]       |
| 170 | 8905334083175 | GL071BRN | 469060400005 | BROWN   |     10 |    10 | [0]       |
| 171 | 8905334083168 | GL071BRN | 469060400006 | BROWN   |     11 |     5 | [0]       |
| 172 | 8905334083151 | GL071TAN | 469060401001 | TAN     |      6 |     5 | [0]       |
| 173 | 8905334083144 | GL071TAN | 469060401002 | TAN     |      7 |    10 | [0]       |
| 174 | 8905334083137 | GL071TAN | 469060401003 | TAN     |      8 |    15 | [0]       |
| 175 | 8905334083120 | GL071TAN | 469060401004 | TAN     |      9 |    15 | [0]       |
| 176 | 8905334083113 | GL071TAN | 469060401005 | TAN     |     10 |    10 | [0]       |
| 177 | 8905334083106 | GL071TAN | 469060401006 | TAN     |     11 |     5 | [0]       |
| 178 | 8905334083090 | GL081BLK | 469060402001 | BLACK   |      6 |     7 | [0]       |
| 179 | 8905334083083 | GL081BLK | 469060402002 | BLACK   |      7 |    14 | [0]       |
| 180 | 8905334083076 | GL081BLK | 469060402003 | BLACK   |      8 |    21 | [0]       |
| 181 | 8905334083069 | GL081BLK | 469060402004 | BLACK   |      9 |    21 | [0]       |
| 182 | 8905334083052 | GL081BLK | 469060402005 | BLACK   |     10 |    14 | [0]       |
| 183 | 8905334083045 | GL081BLK | 469060402006 | BLACK   |     11 |     7 | [0]       |
| 184 | 8905334083038 | GL081BRN | 469060403001 | BROWN   |      6 |     5 | [0]       |
| 185 | 8905334083021 | GL081BRN | 469060403002 | BROWN   |      7 |    10 | [0]       |
| 186 | 8905334083014 | GL081BRN | 469060403003 | BROWN   |      8 |    15 | [0]       |
| 187 | 8905334083007 | GL081BRN | 469060403004 | BROWN   |      9 |    15 | [0]       |
| 188 | 8905334082994 | GL081BRN | 469060403005 | BROWN   |     10 |    10 | [0]       |
| 189 | 8905334082987 | GL081BRN | 469060403006 | BROWN   |     11 |     5 | [0]       |
| 190 | 8905334082796 | GL101BLK | 469060407001 | BLACK   |      6 |    10 | [0]       |
| 191 | 8905334082789 | GL101BLK | 469060407002 | BLACK   |      7 |    20 | [0]       |
| 192 | 8905334082772 | GL101BLK | 469060407003 | BLACK   |      8 |    30 | [0]       |
| 193 | 8905334082765 | GL101BLK | 469060407004 | BLACK   |      9 |    30 | [0]       |
| 194 | 8905334082758 | GL101BLK | 469060407005 | BLACK   |     10 |    20 | [0]       |
| 195 | 8905334082741 | GL101BLK | 469060407006 | BLACK   |     11 |    10 | [0]       |
| 196 | 8905334082734 | GL101BRN | 469060408001 | BROWN   |      6 |    10 | [0]       |
| 197 | 8905334082727 | GL101BRN | 469060408002 | BROWN   |      7 |    20 | [0]       |
| 198 | 8905334082710 | GL101BRN | 469060408003 | BROWN   |      8 |    30 | [0]       |
| 199 | 8905334082703 | GL101BRN | 469060408004 | BROWN   |      9 |    30 | [0]       |
| 200 | 8905334082697 | GL101BRN | 469060408005 | BROWN   |     10 |    20 | [0]       |
| 201 | 8905334082680 | GL101BRN | 469060408006 | BROWN   |     11 |    10 | [0]       |
| 202 | 8905334082673 | GL101TAN | 469060409001 | TAN     |      6 |    10 | [0]       |
| 203 | 8905334082666 | GL101TAN | 469060409002 | TAN     |      7 |    20 | [0]       |
| 204 | 8905334082659 | GL101TAN | 469060409003 | TAN     |      8 |    30 | [0]       |
| 205 | 8905334082642 | GL101TAN | 469060409004 | TAN     |      9 |    30 | [0]       |
| 206 | 8905334082635 | GL101TAN | 469060409005 | TAN     |     10 |    20 | [0]       |
| 207 | 8905334082628 | GL101TAN | 469060409006 | TAN     |     11 |    10 | [0]       |
| 208 | 8905334082611 | GL111BLK | 469060410001 | BLACK   |      6 |     5 | [0]       |
| 209 | 8905334082604 | GL111BLK | 469060410002 | BLACK   |      7 |    10 | [0]       |
| 210 | 8905334082598 | GL111BLK | 469060410003 | BLACK   |      8 |    15 | [0]       |
| 211 | 8905334082581 | GL111BLK | 469060410004 | BLACK   |      9 |    15 | [0]       |
| 212 | 8905334082574 | GL111BLK | 469060410005 | BLACK   |     10 |    10 | [0]       |
| 213 | 8905334082567 | GL111BLK | 469060410006 | BLACK   |     11 |     5 | [0]       |
| 214 | 8905334082970 | GL091BLK | 469060404001 | BLACK   |      6 |     5 | [0]       |
| 215 | 8905334082963 | GL091BLK | 469060404002 | BLACK   |      7 |    10 | [0]       |
| 216 | 8905334082956 | GL091BLK | 469060404003 | BLACK   |      8 |    15 | [0]       |
| 217 | 8905334082949 | GL091BLK | 469060404004 | BLACK   |      9 |    15 | [0]       |
| 218 | 8905334082932 | GL091BLK | 469060404005 | BLACK   |     10 |    10 | [0]       |
| 219 | 8905334082925 | GL091BLK | 469060404006 | BLACK   |     11 |     5 | [0]       |
| 220 | 8905334082918 | GL091BRN | 469060405001 | BROWN   |      6 |     7 | [0]       |
| 221 | 8905334082901 | GL091BRN | 469060405002 | BROWN   |      7 |    14 | [0]       |

In [ ]:
fir = 1
sum = df1.qty[0]
df1.cartons[0] = fir
for x in range(1, 168):
  if x <= no:
    continue
  curr = df1.qty[x]
  if curr <= 10:
    if sum+curr < 10:
      print("here",x,df1.qty[x],"---",sum, fir)
      df1.cartons[x] = fir
      sum = sum+curr
    if sum+curr >= 10:
      #req = curr-(curr+sum-10)
      req = 10-sum
      avail = curr
      #df1.loc[x] = [df1.ean[x], df1.style[x], df1.art[x], df1.COLOR[x], df1.SIZE[x], avail-req, fir]
      df1.loc[x] = [df1.ean[x], df1.stylee[x], df1.art[x], df1.COLOR[x], df1.SIZE[x], avail-req, fir]
      avail = avail-req
      fir+=1
      df1.loc[x+1] = [df1.ean[x], df1.stylee[x], df1.art[x], df1.COLOR[x], df1.SIZE[x], avail, fir]
      no = x+1
      #sum = sum+req
      #f1.cartons[x].append(fir)
      #fir+=1
      sum = 0
  else:
    #print("here",df1.qty[x],"---",sum)
    sum = sum+curr
    boxes = int(sum/10)
    t = x
    fir+=1
    for i in range(fir, fir+boxes):
      df1.loc[t] = [df1.ean[x], df1.stylee[x], df1.art[x], df1.COLOR[x], df1.SIZE[x], 10, fir]
      t+=1
      print(boxes)
      #df1.cartons[x].append(fir)
      fir+=1
    if sum//10 >0:
      sum = sum//10
      #df1.loc[t] = [df1.ean[x], df1.stylee[x], df1.art[x], df1.COLOR[x], df1.SIZE[x], sum, fir]
    else:sum = 0
    no = t-1

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()

1
here 6 7 --- 0 5
2
2
1
here 11 7 --- 1 11
1
2
2
1
here 17 7 --- 1 19
1
here 24 7 --- 0 24
2
2
1
here 29 7 --- 1 30
1
2
2
1
here 35 7 --- 1 38
1
here 42 5 --- 0 43
1
1
3
3
3
2
2
3
3
3
here 60 5 --- 3 62
1
1
here 66 7 --- 0 68
2
2
1
here 71 7 --- 1 74
1
1
1
1
here 77 6 --- 1 83
1
here 84 5 --- 0 88
1
1
here 90 5 --- 0 94
1
1
here 96 7 --- 0 100
2
2
1
here 101 7 --- 1 106
1
3
3
3
2
2
3
3
3
3
3
3
1
here 132 5 --- 0 134
1
1
here 138 7 --- 0 140
2
2
1
here 143 7 --- 1 146
1
2
2
1
here 149 7 --- 1 154
1
here 156 7 --- 0 159
2
2
1
here 161 7 --- 1 165
1
2
2
1
here 167 7 --- 1 173

In [ ]:
print("\n DECREMENTED FOR LOOP") 
for i in range(4, -1, -1): 
   print(i)

 DECREMENTED FOR LOOP
4
3
2
1
0